#!/bin/bash

# Read the current value and maximum value of the btightness
function readValue {
    read -r curvalue < $path"brightness"
    read -r maxvalue < $path"max_brightness"
    minvalue=0
}

# Write / Set a vlaue for the brightness
function writeValue {
    if [ $1 -lt 0 ]; then
        value=0
    elif [ $1 -gt $maxvalue ]; then
        value=$maxvalue
    else
        value=$1
    fi
    echo "$value" > $path"brightness"
}

# Acquire the right brightness file
# -k: Keyboard backlight
# -d: Display backlight
# Change the following path to yours!!!
if [ $1 == '-k' ]; then
    path="/sys/devices/platform/asus-nb-wmi/leds/asus::kbd_backlight/"
elif [ $1 == '-d' ]; then
    path="/sys/class/backlight/intel_backlight/"
else
    exit
fi

# Read arguments and set brightness
readValue
if [ $2 == '-set' ]; then
    writeValue $3
elif [ $2 == '-inc' ]; then
    writeValue $[$curvalue+$3]
elif [ $2 == '-dec' ]; then
    writeValue $[$curvalue-$3]
fi

